# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Current Microsoft Azure Sponsorship(b686535a-348d-4a99-9f47-b2466acf759e)'
    appType: 'webAppLinux'
    appName: 'Intersection-Advanced-Analytics'
    deployToSlotOrASE: true
    resourceGroupName: 'ldace_rg_5153'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.9'
    startUpCommand: 'docker run -p 8000:8000 imammasleap/cmrpack:v3'