# Generated by Django 4.1.3 on 2023-02-03 09:03

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_bin',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/media')), upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_xml',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/media')), upload_to='models/'),
        ),
    ]
